# Generated by Django 2.1.2 on 2019-04-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=64)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('storyId', models.IntegerField()),
                ('commentContent', models.CharField(max_length=256)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('imgId', models.AutoField(primary_key=True, serialize=False)),
                ('imgName', models.CharField(default='no_name', max_length=256)),
                ('imgUrl', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('storyId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=256)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('commitFlag', models.CharField(default='false', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
