# Generated by Django 2.1.2 on 2019-05-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='imgUrl',
            field=models.ImageField(upload_to=''),
        ),
    ]
