# Generated by Django 2.1.1 on 2018-10-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cId', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=256)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.CharField(max_length=256),
        ),
    ]
