# Generated by Django 2.1.2 on 2019-07-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='commitFlag',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
