# Generated by Django 2.1.1 on 2018-10-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181006_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='commentContent',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='cId',
            new_name='commentId',
        ),
    ]
