# Generated by Django 2.1.2 on 2019-07-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190712_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgOnlyUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.ImageField(upload_to='')),
            ],
        ),
    ]
