# Generated by Django 2.1.2 on 2018-10-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181006_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commitFlag',
            field=models.CharField(default='false', max_length=64),
        ),
    ]
