# Generated by Django 2.1.2 on 2018-10-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_comment_commitflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commitFlag',
        ),
        migrations.AddField(
            model_name='story',
            name='commitFlag',
            field=models.CharField(default='false', max_length=64),
        ),
    ]
