# Generated by Django 2.1.2 on 2019-07-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_imgonlyupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgonlyupload',
            name='imgUrl',
            field=models.ImageField(upload_to='./us/'),
        ),
    ]
