# Generated by Django 2.1.2 on 2019-08-02 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190712_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='addTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
