# Generated by Django 2.1.2 on 2018-10-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20181017_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(default='false', max_length=256)),
                ('img_url', models.ImageField(upload_to='img')),
            ],
        ),
    ]
