# Generated by Django 2.1.2 on 2018-10-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20181021_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img_url',
            field=models.ImageField(upload_to='media'),
        ),
    ]
